name: fast_gbk_example
version: 0.0.1
description: A sample command-line application for fast_gbk

publish_to: none

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0
  fast_gbk:
    path: ../
#dev_dependencies:
#  unittest: any
