name: fast_gbk
description: a fast gbk codec, support GBK encoding and decoding with stream api.
version: 1.0.0
homepage: https://github.com/lixiangthinker/fast_gbk

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  dio: ^4.0.0-beta7
